---
title: Hugo Interactive Charts
author: ~
date: '2017-11-11'
categories: ["R"]
tags: ["R Markdown", "Hugo", "websites"]
#menu: "main"
disable_profile: false
disable_widgets: true
banner: "http://www.unc.edu/~nielsen/soci709/m1/m1005.gif"
---

```{r setup, include=F}
knitr::opts_chunk$set(
  echo = T, 
  warning = F, 
  error = F, 
  message = F)
```


# Hey hello

```{r}
par(mar = c(0, 1, 0, 1))
pie(
  c(280, 60, 20),
  c('Sky', 'Sunny side of pyramid', 'Shady side of pyramid'),
  col = c('#0292D8', '#F7EA39', '#C4B632'),
  init.angle = -50, border = NA
)
```

```{r, echo = T}
library(ggplot2)
library(plotly)
gg1<-ggplot(mtcars, aes(disp, mpg)) + 
  geom_point()

ggplotly(gg1)
```

```{r}
load('data/project_macro.Rdata')
library(sunburstR)
library(htmltools)

project_macro %>%
  filter(year %in% 2000) %>% #
  rename(value = exports) %>%
  select(region, country, value) %>%
  mutate(region = stringr::str_replace_all(region, "\\(.*?\\)", "")) %>%
  mutate(region = stringr::str_replace_all(region, "-", " ")) %>%
  arrange(region, value) %>%
  mutate(seqs = paste(region, country, sep = "-")) %>%
  select(seqs, value) %>%
  sunburst(count = T, percent = T)
```








